name: Build Java Game

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Extract tag version
      run: echo "REVISION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Set version in pom.xml
      run: mvn versions:set -DnewVersion=$REVISION

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: target/Dungeon_Master-${{ env.REVISION }}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
